### ISSUE TITLE
Listing Tranches on Auctions leads to undefined reading length error

### ISSUE THREAD

**Issue by schizobrah** [IrrigationProtocol/BugBounty#7]
TypeError: Cannot read properties of undefined (reading 'length')
  at V (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-11.js:1:168150)
  at va (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:60111)
  at Mu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:105038)
  at As (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:90901)
  at Rs (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:90826)
  at xs (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:88166)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:46516
  at n.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:514297)
  at Xo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:46225)
  at ti (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:46461)
  at ei (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:46396)
  at bs (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:84932)
  at Aa (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:63768)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-8.js:1:156578

**Comment by schizobrah** [comment]
issue was not duplicated on other machines. most likely a bug from individual wallet or computer.
issue spontaneously resolved.
